### ISSUE TITLE
Pretrained Model Release Timeline

### ISSUE THREAD

**Issue by SrijDude3416** [xtalpi-xic/SC-MAMBA2#1]
Hi, just curious when we can expect pretrained models to be released.

Thanks

**Comment by xtalpi-xic** [comment]
Thank you for your inquiry. We will release our pre-trained model next month.

**Comment by SrijDude3416** [comment]
Hi, thank you for your response.
Can we expect these models to be released sometime in early-December?

**Comment by SrijDude3416** [comment]
Hi, just following up on this. Thanks for the help

**Comment by xtalpi-xic** [comment]
You can find the model link in the readme now, thanks.
